from __future__ import annotations

import csv
import html
import json
import math
import os
import queue
import socket
import threading
import time
import unicodedata
from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlencode
from urllib.request import urlopen

import cv2
import numpy as np

CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30
USE_DSHOW_ON_WINDOWS = True
DETECTION_EVERY_N_FRAMES = 1

WINDOW_NAME = "Tram mat dat tich hop AI"
FULLSCREEN = True

POSE_MODEL_PATH = "yolov8n-pose.pt"
POSTURE_MODEL_CANDIDATES = [
    "Model/Posture/weights/best.pt",
]
RESCUE_MODEL_CANDIDATES = [
    "Model/Rescue/weights/best.pt",
]
POSE_CONFIDENCE = 0.50
POSTURE_CONFIDENCE = 0.45
RESCUE_CONFIDENCE = 0.80
RESCUE_HIGH_CONF_THRESHOLD = 0.85
RESCUE_IOU_THRESHOLD = 0.20
TRACKER_CONFIG = "bytetrack.yaml"

POSTURE_MODEL_WEIGHT = 0.85   
POSE_POSTURE_WEIGHT = 0.15    
POSTURE_FUSION_MIN_CONFIDENCE = 0.50 
POSTURE_FUSION_MIN_MARGIN = 0.05      
VICTIM_FUSION_THRESHOLD = 0.85

SIMULATE_WHEN_MODEL_MISSING = False
FALLBACK_SYNTHETIC_FRAME = True

WARNING_THRESHOLD = 55
DANGER_THRESHOLD = 85
AUTO_SAVE_MIN_SCORE = 85
FOCUS_SWITCH_SCORE_MARGIN = 15
POSTURE_MODE = "detailed" 
POSTURE_CONFIRM_WINDOW_FRAMES = 10
POSTURE_LYING_CONFIRM_FRAMES = 2
POSTURE_UPRIGHT_CLEAR_FRAMES = 2
POSTURE_STANDING_CONFIRM_FRAMES = 3
POSTURE_SITTING_CONFIRM_FRAMES = 3
POSTURE_WEAK_CONFIRM_FRAMES = 6
POSTURE_SITTING_TO_STANDING_CONFIRM_FRAMES = 6
POSTURE_STANDING_TO_SITTING_CONFIRM_FRAMES = 5
POSTURE_MAJORITY_THRESHOLD = 0.60
LYING_RATIO_THRESHOLD = 1.6
STANDING_RATIO_THRESHOLD = 1.65
LYING_KEYPOINT_RATIO_THRESHOLD = 1.30
STANDING_UPPER_LEG_TORSO_RATIO_MIN = 0.95
SITTING_UPPER_LEG_TORSO_RATIO_MAX = 0.80
CENTER_SMOOTHING_FRAMES = 8
CENTER_JITTER_THRESHOLD = 30
MOVING_THRESHOLD = 80
MOTION_WINDOW_SECONDS = 3
STILLNESS_SECONDS = 20
LONG_IMMOBILE_SECONDS = 15
IMMOBILE_MOTION_SCORE = 20
MIN_POSTURE_BBOX_SIZE = 35
POSTURE_LOW_CONFIDENCE = 0.35
DROP_TARGET_SECONDS = 8
AUTO_DANGER_LOG_COOLDOWN_SECONDS = 60
AUTO_DANGER_SCORE_DELTA = 15
AUTO_DANGER_SKIP_MESSAGE_SECONDS = 10

HAND_RAISE_HOLD_SECONDS = 1.0
WAVING_WINDOW_SECONDS = 2.0
WAVING_MIN_DIRECTION_CHANGES = 3
WRIST_MOVE_THRESHOLD = 60
GESTURE_HOLD_AFTER_DETECT_SECONDS = 2.0
HAND_RAISE_MARGIN_PIXELS = 40

ROI_ENABLED = False
SHOW_ROI_IN_CLEAN_MODE = True
ROI_LABEL = "VUNG NGUY HIEM / DANGER ROI"
ROI_CONFIG_FILENAME = "roi_config.json"
ROI_POINTS: list[tuple[int, int]] = []
ROI_EDIT_MODE = False
SHOW_SKELETON = False
SHOW_CROSSHAIR = False
ROI_EDIT_POINTS: list[tuple[int, int]] = []
ROI_BASE_SCORE = 10
ROI_CONTEXT_BONUS_SCORE = 10
ROI_MAX_SCORE = 30
ROI_NORMAL_PERSON_SCORE_CAP = 20

WEATHER_ENABLED = True
WEATHER_PROVIDER = "open_meteo"
WEATHER_LOCATION_NAME = "Hà Nội"
WEATHER_LAT = 21.0285
WEATHER_LON = 105.8542
WEATHER_UPDATE_INTERVAL_SECONDS = 600
INTERNET_CHECK_INTERVAL_SECONDS = 45
INTERNET_CHECK_TIMEOUT_SECONDS = 1.0
WEATHER_HTTP_TIMEOUT_SECONDS = 4.0

SAVE_COOLDOWN_SECONDS = 10

SAVE_REPLAY_VIDEO = True
REPLAY_PRE_SECONDS = 5
REPLAY_POST_SECONDS = 5
REPLAY_FPS = 20
REPLAY_CODEC = "mp4v"
REPLAY_FALLBACK_CODEC = "XVID"
REPLAY_MIN_VALID_BYTES = 10 * 1024
REPLAY_MIN_FRAMES = 20

GENERATE_REPORT_ON_EXIT = True

